### ISSUE TITLE
infinitive verb definition bug

### ISSUE THREAD

**Issue by hellophia** [seth-js/yomichan-es#10]
hello :) thank you so much for making this, I used yomichan/yomitan so much while learning japanese and I just started spanish and was overjoyed that I could keep using one of my favorite extensions.

I want to note I'm not using your work as intended, I did get the modified version of yomichan working but then had the thought, I wonder if I can just plug this dictionary into yomitan? and it worked, mostly! but I'm encountering some bugs. I totally understand if you're not up for addressing this since it's not the intended usage, feel free to close the issue if that's the case.

the bug I'm seeing is that when I scan a conjugated verb, it doesn't show me the definition of the verb. for example, when I look up "sale" I get the following definition: non-lemma verb {sale -> salir} third-person singular present indicative of salir (->salir), without seeing the actual definition for salir.

another example, when I scan the sentence you use in your example image, "Ahora eres libre," for libre it only gives me the following definition: non-lemma verb {libre -> librar} first/third-person singular present subjunctive (->librar) verb {libre -> librar} third-person singular imperative (->librar), when I would hope to see the definition for the infinitive as seen in your example.

again, I realize this might not be a use case you feel the need to support, either way thank you very much for your work, it's been a great help!

**Comment by seth-js** [comment]
I'm glad it's been helping you with your Spanish studies. You're having these issues because Yomitan handles Spanish inflections differently than my custom version of Yomichan does.

At the beginning of this year, Yomitan didn't support:

- languages with capital letters
- languages with spaces
- inflections for any other language but Japanese

However, thanks to the work of @StefanVukovic99, Yomitan now handles dozens of languages, and includes nearly all of the features that my edits covered.

If you'd like to study Spanish with Yomitan, I recommend using the [kaikki-to-yomitan](https://github.com/themoeway/kaikki-to-yomitan/releases) dictionaries instead.

Specifically, download and import these two:

- [kty-es-en.zip](https://github.com/themoeway/kaikki-to-yomitan/releases/download/24.04.08.0/kty-es-en.zip)
- [kty-es-en-ipa.zip](https://github.com/themoeway/kaikki-to-yomitan/releases/download/24.04.08.0/kty-es-en-ipa.zip)

Make sure that you're using the latest Yomitan release.

**Comment by hellophia** [comment]
thank you so much for pointing me in the right direction, I appreciate it!
