### ISSUE TITLE
The 'Model' in the custom Yomichan doesn't work so I cannot create cards

### ISSUE THREAD

**Issue by HIKORIN01** [seth-js/yomichan-es#2]
I don't think it's registering, so whenever I try to create a card it won't let me

**Comment by seth-js** [comment]
The model is set up for my deck. You need to change the deck and model selection to work with yours. If you want to keep the layout I use, you need to have the same fields I use. The deck name and model name can be whatever you want.

![deck](https://user-images.githubusercontent.com/83692925/216411010-0c7043a4-5f98-4852-8932-106cb2de680a.png)

![yomichan-fields](https://user-images.githubusercontent.com/83692925/216411863-9a60d5f7-2c1e-4c4c-ba5b-1a22023b33cf.png)

Make sure you have the AnkiConnect addon installed.

**Comment by HIKORIN01** [comment]
I have AnkiConnect installed, but even though I copied everything into a specific model I keep getting a 'Template render error' message. Am I doing something wrong?

**Comment by seth-js** [comment]
I'm setting everything up on another computer. Let me see if I get the error. Sharing the entire Yomichan settings JSON may be overkill. I might just rewrite the instructions to include relevant information to get the Forvo server working with Yomichan and turning `Layout-aware scanning` on.

**Comment by seth-js** [comment]
I just set it up, and everything's working. After creating a new Anki deck and model and setting up the fields to match with what was provided in the settings JSON, I turned the `Enable Anki integration` option off and on. This updates Yomichan's data on what decks and models are currently in Anki. Can you show me your `Anki card format` window?

**Comment by HIKORIN01** [comment]
![pesos](https://user-images.githubusercontent.com/122656376/216455554-331fe824-a0e9-492f-b630-74e0e0d64086.PNG)

**Comment by seth-js** [comment]
There's a typo in the `Sentence` field. `</strong?` should be `</strong>`.

**Comment by HIKORIN01** [comment]
Changed it, still the same error

**Comment by seth-js** [comment]
Can you post an image of the `Template render error` message? Also, you may want to try going to the bottom of the settings page and clicking `Reset Settings`. After doing that you need to:

- Turn on the `Advanced` option on the bottom left.
- Search the page for `Layout-aware scanning` and turn it on.
- Change the `Text scan length` to `32`.
- Click `Configure audio playback sources…`.
- Change `JapanesePod101` to `Custom URL (JSON)`.
- Set the URL to `http://localhost:8770/?term={term}`.

**Comment by HIKORIN01** [comment]
Side Note: Is it normal to have to reinstall the dictionary every time close and open the Firefox profile?

**Comment by HIKORIN01** [comment]
![thealamo](https://user-images.githubusercontent.com/122656376/216629030-becb85a6-2d9e-41df-b458-59ef4af23b1c.PNG)

It goes on to list the other parts of the card afterwards.

**Comment by HIKORIN01** [comment]
Also the changes you suggested didn't change anything.

When I reset my settings and followed the instructions I wasn't about to select anything in the deck and model area, that is, nothing would come up on the popup.

Then, after re-importing the settings, the same 'template render error' issue occurred.

**Comment by seth-js** [comment]
Sorry for wasting all your time like that. I've been trying yomichan-es on different computers and never got the same error, but I didn't think to try out the Firefox setup. The second I set everything up on Firefox instead of Chromium,  I also received the error. Looking inside the console, I see this error: `Content Security Policy: The page’s settings blocked the loading of a resource at eval (“default-src”).` The error happens in `handlebars.min.js`. [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) is preventing Yomichan from loading stuff it needs for the handlebars templates.

I'll have to figure out how to fix this now. In the meantime, can you try using this on a Chromium-based browser instead (Chrome, Brave, etc.)? Make sure you import the same settings JSON. I realized that the instructions I wrote earlier are still missing some necessary changes.

>Side Note: Is it normal to have to reinstall the dictionary every time close and open the Firefox profile?

I also just noticed this too. It's weird because when I first released yomichan-ru, Firefox would have everything set up even if the browser restarted. It looks like Firefox changed how that works. Once again, just use the Chromium setup while I try to figure out what's going on. I may have to create a Firefox addon file for all the settings to stay.

**Comment by seth-js** [comment]
Everything is now working with Firefox. I'm no longer getting the `Template render error` message. Yomichan settings and the dictionary are saved even after restarting the browser. I ended up downloading a stable version of Yomichan specifically for Firefox, and applying the changes to that. Now all the problems are gone. I also removed some CSS I accidentally left in the `Custom CSS` option. These fixes will be uploaded some time tomorrow. The readme will also be slightly changed.

**Comment by seth-js** [comment]
I did the changes. Hopefully everything has been uploaded correctly. Reset Yomichan if it is still installed, remove the dictionary, remove the add-on, and then follow the new instructions. Now I'll have to update yomichan-fr as well.

**Comment by HIKORIN01** [comment]
Even with the new directions and the new settings file I am still getting the same error.

**Comment by HIKORIN01** [comment]
Was there a new version of the dictionary?

**Comment by seth-js** [comment]
I just set up the Firefox version on another computer, and the error's not coming up with the new instructions. At this point, I think it has something to do with how your personal Firefox is set up. There's nothing else I can do. My recommendation is for you to use the Chromium version of the add-on.
